fix node-sqlite3 dependency in ARM builds (#131)

diff --git a/.github/workflows/docker-image-test.yml b/.github/workflows/docker-image-test.yml
--- a/.github/workflows/docker-image-test.yml
+++ b/.github/workflows/docker-image-test.yml
@@ -7,32 +7,53 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: false
       matrix:
+        platform: [linux/amd64, linux/arm64/v8, linux/arm/v7]
         dockerfile: [Dockerfile, alpine/Dockerfile]
     steps:
       - name: Set env
         run: echo "mount_dir=$(mktemp -d)" >> $GITHUB_ENV
 
       - name: Checkout
-        uses: actions/checkout@v1
+        uses: actions/checkout@v2
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
+
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v1
+        with:
+          install: true
 
       - name: Build Docker image
-        run: docker build -t thelounge -f ${{ matrix.dockerfile }} .
+        run: docker build --platform ${{ matrix.platform }} --load -t thelounge -f ${{ matrix.dockerfile }} .
 
       - name: Start Docker container
-        run: docker run --user "$UID" -v "${mount_dir}:/var/opt/thelounge" -d -p 9001:9000 --name thelounge thelounge
+        run: docker run --platform ${{ matrix.platform }} --user "$UID" -v "${mount_dir}:/var/opt/thelounge" -d -p 9001:9000 --name thelounge thelounge
 
       - name: Check TheLounge version
         run: docker exec thelounge thelounge --version | grep --color=never -E "^v[0-9]\.[0-9]\.[0-9]" | cut -c 2- | grep -f /dev/stdin ${{ matrix.dockerfile }}
 
-      - name: Wait for server to (hopefully) start
-        run: sleep 3
-
       - name: Check HTML output
-        run: curl -sL localhost:9001 | grep "<title>The Lounge</title>"
+        run: |
+          # Retry Wait for server to start.
+          for i in {1..10}; do
+            (curl -sL localhost:9001 | grep "<title>The Lounge</title>") && s=0 && break || s=$? && sleep 1;
+          done
+          exit $s
+
+      - name: Check for no ERROR logs
+        run: docker logs thelounge | grep "\[ERROR\]" && exit 1 || exit 0
 
       - name: Check for config.js to be created in the mounted host system directory
         run: stat "${mount_dir}/config.js"
 
+      - name: Container context
+        if: always()
+        run: docker exec thelounge uname -a
+
       - name: Logs
+        if: always()
         run: docker logs thelounge
